### ISSUE TITLE
Only up to 2 condition terms can be specified

### ISSUE THREAD

**Issue by Spiritspeak** [vandenman/DstarM#14]
When I run the following code,

```
fit2<-estDstarM(formula = is_pull ~ decisiongrab + is_target * is_spidertask, 
               data=ds, tt=(0:100)/100, verbose = T)
```
I get this error:
```
Error in getData(formula, data, verbose = verbose) : 
  More than 3 columns remained after specifying model.frame(formula, data = data)
```

I had a look in the getData() function and it seems to simply check the number of terms on the right-hand side, and error if there are more than 3 of them (incl the reaction time term). However, this is inconsistent with the help file: there, it is suggested that you can specify as many conditions as you want.

**Comment by vandenman** [comment]
Thanks for reporting the issue! Can you tell/ show me the structure of `ds`? That way I can more easily reproduce the issue.

**Comment by Spiritspeak** [comment]
It's a data.frame with 4 columns: is_pull (dichotomous, factor) is_target (dichotomous, factor), is_spidertask (dichotomous, factor) and decisiongrab (continuous, numeric)

**Comment by vandenman** [comment]
After giving this some thought I decided to update the documentation to reflect that there should only be a single column that indicates the conditions and that multiple column must be pasted together manually. Otherwise, it's rather confusing which column of the restriction matrix refers to which condition if the conditions are created internally.
